_target_: lambo.models.lm_elements.LanguageModel
name: lanmt_cnn

model:
  _target_: lambo.models.shared_elements.mCNN
  tokenizer: ${tokenizer}
  max_len: ${task.max_len}
  embed_dim: 64
  latent_dim: 16
  out_dim: 16
  kernel_size: 5
  p: 0.
  layernorm: True
  max_len_delta: 8

batch_size: 32
num_epochs: 128
patience: 32
lr: 1e-3
max_shift: 0
mask_ratio: 0.125