data_pruning: True 
data_preserved_ratio: 0.2 

n_epochs: 200 
batch_size: 128 

forward_lr: 0.0003
forward_lr_decay: 0.98 

alpha: 0.1
alpha_lr: 0.01 
overestimation_limit: 0.5
particle_lr: 0.05
particle_gradient_steps: 50
entropy_coefficient: 0.0
mmd_param: 2
discriminator_lr: 0.001
discriminator_betas: (0.5, 0.999)
rep_lr: 0.0003
noise_std: 0.0
