_target_: pymoo.algorithms.moo.nsga2.NSGA2
pop_size: ${task.batch_size}
n_offsprings: null
sampling:
  _target_: lambo.optimizers.sampler.CandidateSampler
crossover:
  _target_: pymoo.factory.get_crossover
  name: int_sbx
  prob: 0.
  eta: 16
mutation:
  _target_: lambo.optimizers.mutation.LocalMutation
  prob: 1.
  eta: 16
  safe_mut: False
eliminate_duplicates: True