_target_: lambo.models.deep_ensemble.DeepEnsemble
model: mCNN
model_kwargs:
  embed_dim: 64
  latent_dim: 16
  out_dim: ${task.obj_dim}
  kernel_size: 5
  p: 0.
  layernorm: True
  max_len: ${task.max_len}
  max_len_delta: 0

ensemble_size: 4
num_epochs: 256
eval_period: 2
bootstrap_ratio: 0.632
min_num_train: 128
weight_decay: 1e-4
holdout_ratio: 0.2
early_stopping: True
lr: 1e-3
bs: 32
patience: 32
max_shift: 0
mask_size: 0
