_target_: lambo.models.gp_models.SingleTaskExactGP
max_shift: 0
mask_size: 0
bootstrap_ratio: null
min_num_train: 128
task_noise_init: 1e-2
gp_lr: 5e-3
enc_lr: 5e-3
bs: 128
num_epochs: 512
holdout_ratio: 0.2
early_stopping: True
patience: 32
eval_period: 2
feature_dim: 16
out_dim: ${task.obj_dim}
encoder_wd: 1e-4
covar_module:
  _target_: gpytorch.kernels.MaternKernel
  ard_num_dims: ${surrogate.feature_dim}
  batch_shape:
    - ${task.obj_dim}
  lengthscale_prior:
    _target_: gpytorch.priors.NormalPrior
    loc: 0.7
    scale: 1e-2
likelihood:
  _target_: gpytorch.likelihoods.GaussianLikelihood
  batch_shape:
    - ${task.obj_dim}
  noise_constraint:
    _target_: gpytorch.constraints.GreaterThan
    lower_bound: 1e-4
